server:
  port: 8486

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

pdf-service:
  url: ${PDF_SERVICE_URL}

idam:
  s2s-auth:
    url: ${S2S_URL}
    secret: ${S2S_SECRET}
    name: ${S2S_NAME:sendletterconsumer}

servicebus:
  connectionString: ${SERVICE_BUS_CONNECTION_STRING:}
  interval: ${SERVICE_BUS_INTERVAL:30000}

ftp:
  hostname: ${FTP_HOSTNAME}
  port: ${FTP_PORT}
  target-folder: ${FTP_TARGET_FOLDER}
  smoke-test-target-folder: ${FTP_SMOKE_TEST_TARGET_FOLDER:SMOKE_TEST}
  reports-folder: ${FTP_REPORTS_FOLDER}
  reports-cron: ${FTP_REPORTS_CRON:0 30 * * * *}
  fingerprint: ${FTP_FINGERPRINT}
  username: ${FTP_USER}
  privateKey: ${FTP_PRIVATE_KEY}
  publicKey: ${FTP_PUBLIC_KEY}
  downtime:
    from: ${FTP_DOWNTIME_FROM:17:00}
    to: ${FTP_DOWNTIME_TO:18:00}

app-insights:
  request-component: off

sendletter:
  producer:
    url: ${SEND_LETTER_PRODUCER_URL}
