server:
  port: 8486

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

pdf-service:
  url: ${PDF_SERVICE_URL}

idam:
  s2s-auth:
    url: ${S2S_URL}
    secret: ${S2S_SECRET}
    name: ${S2S_NAME:sendletterconsumer}

servicebus:
  connectionString: ${SERVICE_BUS_CONNECTION_STRING:}
  interval: ${SERVICE_BUS_INTERVAL:30000}

ftp:
  hostname: ${FTP_HOSTNAME}
  port: ${FTP_PORT}
  fingerprint: ${FTP_FINGERPRINT}
  user: ${FTP_USER}
  password: ${FTP_PASSWORD}
  downtime:
    from: ${FTP_DOWNTIME_FROM:17:00}
    to: ${FTP_DOWNTIME_TO:18:00}

app-insights:
  request-component: off
